/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Entire Dashboard API
 * AI agent session metrics visualization API
 * OpenAPI spec version: 1.0.0
 */
export interface Repository {
  id: number;
  path: string;
  name: string;
  created_at: string;
}

export interface AddRepoRequest {
  path: string;
}

export interface DeleteRepoResponse {
  status: string;
}

export interface DailyStat {
  date: string;
  agent_lines: number;
  human_lines: number;
  total_lines: number;
  agent_percentage: number;
  session_count: number;
}

export interface Session {
  id: number;
  repo_path: string;
  checkpoint_id: string;
  session_id: string;
  agent: string;
  branch: string;
  created_at: string;
  prompt: string;
  agent_lines: number;
  human_added: number;
  human_modified: number;
  human_removed: number;
  total_committed: number;
  agent_percentage: number;
  input_tokens: number;
  output_tokens: number;
  api_call_count: number;
}

export interface SyncResponse {
  total_found: number;
  inserted: number;
  message: string;
}

export interface ErrorResponse {
  message: string;
}

/**
 * Bad request
 */
export type BadRequestResponse = ErrorResponse;

/**
 * Internal server error
 */
export type InternalErrorResponse = ErrorResponse;

export type GetDailyStatsParams = {
/**
 * Filter by repository path
 */
repo?: string;
};

export type GetSessionsParams = {
/**
 * Filter by repository path
 */
repo?: string;
};

export type SyncDataParams = {
/**
 * Sync specific repository only
 */
repo?: string;
};

/**
 * @summary List registered repositories
 */
export type getReposResponse200 = {
  data: Repository[]
  status: 200
}

export type getReposResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type getReposResponseSuccess = (getReposResponse200) & {
  headers: Headers;
};
export type getReposResponseError = (getReposResponse500) & {
  headers: Headers;
};

export type getReposResponse = (getReposResponseSuccess | getReposResponseError)

export const getGetReposUrl = () => {


  

  return `/api/repos`
}

export const getRepos = async ( options?: RequestInit): Promise<getReposResponse> => {
  
  const res = await fetch(getGetReposUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getReposResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getReposResponse
}
  


/**
 * @summary Register a new repository
 */
export type addRepoResponse200 = {
  data: Repository
  status: 200
}

export type addRepoResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type addRepoResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type addRepoResponseSuccess = (addRepoResponse200) & {
  headers: Headers;
};
export type addRepoResponseError = (addRepoResponse400 | addRepoResponse500) & {
  headers: Headers;
};

export type addRepoResponse = (addRepoResponseSuccess | addRepoResponseError)

export const getAddRepoUrl = () => {


  

  return `/api/repos`
}

export const addRepo = async (addRepoRequest: AddRepoRequest, options?: RequestInit): Promise<addRepoResponse> => {
  
  const res = await fetch(getAddRepoUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      addRepoRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: addRepoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as addRepoResponse
}
  


/**
 * @summary Delete a repository and its sessions
 */
export type deleteRepoResponse200 = {
  data: DeleteRepoResponse
  status: 200
}

export type deleteRepoResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type deleteRepoResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type deleteRepoResponseSuccess = (deleteRepoResponse200) & {
  headers: Headers;
};
export type deleteRepoResponseError = (deleteRepoResponse400 | deleteRepoResponse500) & {
  headers: Headers;
};

export type deleteRepoResponse = (deleteRepoResponseSuccess | deleteRepoResponseError)

export const getDeleteRepoUrl = (id: number,) => {


  

  return `/api/repos/${id}`
}

export const deleteRepo = async (id: number, options?: RequestInit): Promise<deleteRepoResponse> => {
  
  const res = await fetch(getDeleteRepoUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteRepoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteRepoResponse
}
  


/**
 * @summary Get aggregated daily statistics
 */
export type getDailyStatsResponse200 = {
  data: DailyStat[]
  status: 200
}

export type getDailyStatsResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type getDailyStatsResponseSuccess = (getDailyStatsResponse200) & {
  headers: Headers;
};
export type getDailyStatsResponseError = (getDailyStatsResponse500) & {
  headers: Headers;
};

export type getDailyStatsResponse = (getDailyStatsResponseSuccess | getDailyStatsResponseError)

export const getGetDailyStatsUrl = (params?: GetDailyStatsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/daily-stats?${stringifiedParams}` : `/api/daily-stats`
}

export const getDailyStats = async (params?: GetDailyStatsParams, options?: RequestInit): Promise<getDailyStatsResponse> => {
  
  const res = await fetch(getGetDailyStatsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getDailyStatsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getDailyStatsResponse
}
  


/**
 * @summary List sessions
 */
export type getSessionsResponse200 = {
  data: Session[]
  status: 200
}

export type getSessionsResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type getSessionsResponseSuccess = (getSessionsResponse200) & {
  headers: Headers;
};
export type getSessionsResponseError = (getSessionsResponse500) & {
  headers: Headers;
};

export type getSessionsResponse = (getSessionsResponseSuccess | getSessionsResponseError)

export const getGetSessionsUrl = (params?: GetSessionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/sessions?${stringifiedParams}` : `/api/sessions`
}

export const getSessions = async (params?: GetSessionsParams, options?: RequestInit): Promise<getSessionsResponse> => {
  
  const res = await fetch(getGetSessionsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getSessionsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getSessionsResponse
}
  


/**
 * @summary Sync data from git shadow branch
 */
export type syncDataResponse200 = {
  data: SyncResponse
  status: 200
}

export type syncDataResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type syncDataResponseSuccess = (syncDataResponse200) & {
  headers: Headers;
};
export type syncDataResponseError = (syncDataResponse500) & {
  headers: Headers;
};

export type syncDataResponse = (syncDataResponseSuccess | syncDataResponseError)

export const getSyncDataUrl = (params?: SyncDataParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/sync?${stringifiedParams}` : `/api/sync`
}

export const syncData = async (params?: SyncDataParams, options?: RequestInit): Promise<syncDataResponse> => {
  
  const res = await fetch(getSyncDataUrl(params),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: syncDataResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as syncDataResponse
}
