// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

type Repository struct {
	ID        int64
	Path      string
	Name      string
	CreatedAt string
}

type Session struct {
	ID              int64
	RepoPath        string
	CheckpointID    string
	SessionID       string
	Agent           string
	Branch          string
	CreatedAt       string
	Prompt          string
	AgentLines      int64
	HumanAdded      int64
	HumanModified   int64
	HumanRemoved    int64
	TotalCommitted  int64
	AgentPercentage float64
	InputTokens     int64
	OutputTokens    int64
	ApiCallCount    int64
}
