// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteRepo = `-- name: DeleteRepo :exec
DELETE FROM repositories WHERE id = ?
`

func (q *Queries) DeleteRepo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRepo, id)
	return err
}

const deleteSessionsByRepoPath = `-- name: DeleteSessionsByRepoPath :exec
DELETE FROM sessions WHERE repo_path = ?
`

func (q *Queries) DeleteSessionsByRepoPath(ctx context.Context, repoPath string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByRepoPath, repoPath)
	return err
}

const getDailyStats = `-- name: GetDailyStats :many
SELECT
    substr(created_at, 1, 10) AS date,
    SUM(agent_lines) AS agent_lines,
    SUM(human_added) AS human_lines,
    SUM(agent_lines) + SUM(human_added) AS total_lines,
    CASE WHEN SUM(agent_lines) + SUM(human_added) > 0
        THEN ROUND(CAST(SUM(agent_lines) AS REAL) / (SUM(agent_lines) + SUM(human_added)) * 100, 1)
        ELSE 0
    END AS agent_percentage,
    COUNT(*) AS session_count
FROM sessions
WHERE (? = '' OR repo_path = ?)
GROUP BY substr(created_at, 1, 10)
ORDER BY date
`

type GetDailyStatsParams struct {
	Column1  interface{}
	RepoPath string
}

type GetDailyStatsRow struct {
	Date            string
	AgentLines      sql.NullFloat64
	HumanLines      sql.NullFloat64
	TotalLines      int64
	AgentPercentage int64
	SessionCount    int64
}

func (q *Queries) GetDailyStats(ctx context.Context, arg GetDailyStatsParams) ([]GetDailyStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDailyStats, arg.Column1, arg.RepoPath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyStatsRow
	for rows.Next() {
		var i GetDailyStatsRow
		if err := rows.Scan(
			&i.Date,
			&i.AgentLines,
			&i.HumanLines,
			&i.TotalLines,
			&i.AgentPercentage,
			&i.SessionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRepoPath = `-- name: GetRepoPath :one
SELECT path FROM repositories WHERE id = ?
`

func (q *Queries) GetRepoPath(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getRepoPath, id)
	var path string
	err := row.Scan(&path)
	return path, err
}

const getRepos = `-- name: GetRepos :many
SELECT id, path, name, created_at FROM repositories ORDER BY created_at
`

func (q *Queries) GetRepos(ctx context.Context) ([]Repository, error) {
	rows, err := q.db.QueryContext(ctx, getRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessions = `-- name: GetSessions :many
SELECT id, repo_path, checkpoint_id, session_id, agent, branch, created_at, prompt,
    agent_lines, human_added, human_modified, human_removed,
    total_committed, agent_percentage,
    input_tokens, output_tokens, api_call_count
FROM sessions
WHERE (? = '' OR repo_path = ?)
ORDER BY created_at DESC
`

type GetSessionsParams struct {
	Column1  interface{}
	RepoPath string
}

func (q *Queries) GetSessions(ctx context.Context, arg GetSessionsParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getSessions, arg.Column1, arg.RepoPath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.RepoPath,
			&i.CheckpointID,
			&i.SessionID,
			&i.Agent,
			&i.Branch,
			&i.CreatedAt,
			&i.Prompt,
			&i.AgentLines,
			&i.HumanAdded,
			&i.HumanModified,
			&i.HumanRemoved,
			&i.TotalCommitted,
			&i.AgentPercentage,
			&i.InputTokens,
			&i.OutputTokens,
			&i.ApiCallCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionExists = `-- name: SessionExists :one
SELECT COUNT(*) FROM sessions WHERE session_id = ?
`

func (q *Queries) SessionExists(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, sessionExists, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const upsertRepo = `-- name: UpsertRepo :one
INSERT INTO repositories (path, name) VALUES (?, ?)
ON CONFLICT(path) DO UPDATE SET name=excluded.name
RETURNING id, path, name, created_at
`

type UpsertRepoParams struct {
	Path string
	Name string
}

func (q *Queries) UpsertRepo(ctx context.Context, arg UpsertRepoParams) (Repository, error) {
	row := q.db.QueryRowContext(ctx, upsertRepo, arg.Path, arg.Name)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const upsertSession = `-- name: UpsertSession :exec
INSERT INTO sessions (
    repo_path, checkpoint_id, session_id, agent, branch, created_at, prompt,
    agent_lines, human_added, human_modified, human_removed,
    total_committed, agent_percentage,
    input_tokens, output_tokens, api_call_count
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(session_id) DO UPDATE SET
    repo_path=excluded.repo_path,
    agent=excluded.agent, branch=excluded.branch,
    created_at=excluded.created_at, prompt=excluded.prompt,
    agent_lines=excluded.agent_lines, human_added=excluded.human_added,
    human_modified=excluded.human_modified, human_removed=excluded.human_removed,
    total_committed=excluded.total_committed, agent_percentage=excluded.agent_percentage,
    input_tokens=excluded.input_tokens, output_tokens=excluded.output_tokens,
    api_call_count=excluded.api_call_count
`

type UpsertSessionParams struct {
	RepoPath        string
	CheckpointID    string
	SessionID       string
	Agent           string
	Branch          string
	CreatedAt       string
	Prompt          string
	AgentLines      int64
	HumanAdded      int64
	HumanModified   int64
	HumanRemoved    int64
	TotalCommitted  int64
	AgentPercentage float64
	InputTokens     int64
	OutputTokens    int64
	ApiCallCount    int64
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSession,
		arg.RepoPath,
		arg.CheckpointID,
		arg.SessionID,
		arg.Agent,
		arg.Branch,
		arg.CreatedAt,
		arg.Prompt,
		arg.AgentLines,
		arg.HumanAdded,
		arg.HumanModified,
		arg.HumanRemoved,
		arg.TotalCommitted,
		arg.AgentPercentage,
		arg.InputTokens,
		arg.OutputTokens,
		arg.ApiCallCount,
	)
	return err
}
